### ISSUE TITLE
[Student import] Remove auto-adding UGent organisation to a person

### ISSUE THREAD

**Issue by netsensei** [ugent-library/old-people-service#36]
# Story

The logic that adds the "Universiteit Gent" organisation to a person has a `TODO` comment in the code: it's unclear if this organization is required for all persons fetched from LDAP.

This logic should temporarily be removed until it's clear whether or not this is a hard requirement.

## Success criteria

- [x] The logic that fetches the UGent organization and auto-adds it to persons needs to be removed from `cmd/import_students.go`

### Screenshots

n/a

### Implementation suggestion

Create a GitHub discussion when finishing this issue.

# Automatic testing scenario

n/a

# Additional information

n/a

# Related issues

- #31

**Comment by nicolasfranck** [comment]
That comment `TODO: require organisation "Universiteit Gent"?` means: if that organization is not present yet, can this command even run, as we have to attach that organization to these users? Without that organization you would be able to see students in the search results but without organization ugent, which would be odd. By the way, that is also the way it is implemented right. I guess that TODO should be removed

**Comment by nicolasfranck** [comment]
cf. https://github.com/ugent-library/people-service/discussions/45
